# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b79e3ce4f5e197347443ab6bab33adc436233ddee81852774d5f0256feb4f3952711413ca2a64f7a7f8476486802c2d7a27494c220dc1d4d3237d630c9ad2815

test:
  secret_key_base: 50002561983e1ca073e640be8dcf76a75911004958416221e42bcca6557a30747cf6b7b20c1413e4ffd3578a35ce280d547f6de6b3cc0cd40d91718a3ea28d81

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
